isi/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls')), # new
    path('users/', include('django.contrib.auth.urls')), # new
    path('tour/', include('tour.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tour/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from tour.views import *

urlpatterns = [
    path('tour/list', TourList.as_view(), name='tourlist'),
    path('tour/<int:id>/', detail_of_tour, name='tour_detail'),
    path('tag/<slug:tag_slug>/',TourList.as_view(), name='tour_list_by_tag'),
    path('category/<int:category_id>/',TourList.as_view(), name='tour_list_by_category'),
    path('contact/', ContactListView.as_view(), name='contact'),
    path('about/', about_detail, name='about'),
    path('members/', MembersListView.as_view(), name='members'),
    # path('booking/<int:id>/', BookingView.as_view(), name='new_booking'),
    path('booking/', BookingView.as_view(), name='booking'),
    path('search/', SearchView.as_view(), name='search'),
    # path('about/', AboutListView.as_view(), name='about'),
    # path('', AboutListView.as_view(), name='about'),
    # path('header/<int:pk>/', ContactDetailViewHeader.as_view(), name='header'),
]

tour/models.py
from datetime import datetime

from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

from taggit.managers import TaggableManager

class Tour(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    views = models.IntegerField(default=0)
    photo = models.ImageField(upload_to='images')
    description = models.TextField()
    category = models.ForeignKey('Category', on_delete=models.CASCADE, related_name='tour')
    tags = TaggableManager()
    popular = models.BooleanField(default=False)
    famous = models.BooleanField(default=False)
    start_day = models.IntegerField()
    start_month = models.CharField(max_length=15)
    how_many_days = models.CharField(max_length=50)


    def __str__(self):
        return f'{self.title}'

    def get_absolute_url(self):
        return reverse('tour_detail', args=[str(self.id)])

class Images(models.Model):
    tour = models.ForeignKey(Tour, on_delete=models.CASCADE, related_name='images')
    images = models.ImageField(upload_to='images')

class Category(models.Model):
    category = models.CharField(max_length=100)
    photo = models.ImageField(upload_to='images/categories')
    description = models.TextField()

    def __str__(self):
        return self.category

class Comment(models.Model):
    tour = models.ForeignKey(Tour, on_delete=models.CASCADE, related_name='comments')
    name = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    date = models.DateField(default=datetime.now)
    username = models.CharField(max_length=50)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.text

class About(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField()
    photo = models.ImageField(upload_to='images')


class Cover(models.Model):
    about = models.ForeignKey(About, on_delete=models.CASCADE, related_name='cover')
    images = models.ImageField(upload_to='images')
    title_cover = models.CharField(max_length=100)
    text_cover = models.CharField(max_length=100)

class Members(models.Model):
    photo = models.ImageField(upload_to='images/members')
    name = models.CharField(max_length=50)
    position = models.CharField(max_length=100)

class Booking(models.Model):
    tour = models.ForeignKey(Tour, on_delete=models.CASCADE, related_name='booking')
    name = models.CharField(max_length=50)
    email = models.EmailField()
    number = models.CharField(max_length=15, help_text='0700 12 34 56')

class Contact(models.Model):
    address = models.CharField(max_length=200, help_text='California, United States')
    address_text = models.CharField(max_length=200, help_text='Santa monica bullevard')
    number = models.CharField(max_length=15, help_text='0777 00 00 00')
    number_text = models.CharField(max_length=200, help_text='Mon to Fri 9am to 6 pm')
    email = models.EmailField(help_text='support@colorlib.com')
    email_text = models.CharField(max_length=200, help_text='Send us your query anytime!')

class Quotes(models.Model):
    text = models.TextField()

    def __str__(self):
        return self.text

tour/forms.py
from .models import *
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

class BookingForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':"Name"}))
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':"Email"}))
    number = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':"Number"}))
    class Meta:
        model = Booking
        fields = ('name', 'email', 'number')

tour/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import TemplateView, DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView
from tour.models import *
from .forms import *
from .models import Comment, Contact
from django.contrib.auth import get_user_model
from users.models import CustomUser
from taggit.models import Tag
from datetime import datetime
from django.db.models import Q


class BookingView(TemplateView):
    template_name = "pages/book-trip.html"

    def get(self, request, *args, **kwargs):
        tours = Tour.objects.all()

        name = request.user
        booking_form = BookingForm()
        return render(request, self.template_name, context={
            'tours': tours,
            'name': name,
            'booking_form': booking_form,
        })

    def post(self, request, *args, **kwargs):
        tour = request.POST.get("id", "")
        tour = Tour.objects.get(pk=tour)
        booking = Booking
        new_booking = None
        booking_form = BookingForm(data=request.POST)
        if booking_form.is_valid():
            print('postko keldi')
            new_booking = booking_form.save(commit=False)
            new_booking.tour = tour
            new_booking.save()
        else:
            print('no valid!!!!!!!!!!!')
            booking_form = BookingForm()
        return redirect('booking')

class TourList(TemplateView):
    template_name = "tour/tour_list.html"

    def get(self, request, tag_slug=None, category_id=None, *args):
        all_tours = Tour.objects.all()
        last_tours = []
        if Tour.objects.all():
            last_tours = Tour.objects.order_by('-created')[:3]
        object_list = Tour.objects.all()
        popular_tours = Tour.objects.filter(popular=True)
        all_tags = Tour.tags.all()
        all_category = Category.objects.all()
        current_time = datetime.now()
        tag = None
        category = None

        if tag_slug:
            tag = get_object_or_404(Tag, slug=tag_slug)
            object_list = object_list.filter(tags__in=[tag])
        if category_id:
            category = get_object_or_404(Category, id=category_id)
            object_list = object_list.filter(category__in=[category])
        paginator = Paginator(object_list, 2)  # По 1 статьи на каждой странице.
        page = request.GET.get('page')
        try:
            tours = paginator.page(page)
        except PageNotAnInteger:
            # Если указанная страница не является целым числом.
            tours = paginator.page(1)
        except EmptyPage:
            # Если указанный номер больше, чем всего страниц, возвращаем последнюю.
            tours = paginator.page(paginator.num_pages)
        return render(request, self.template_name, context={
            'tours': tours,
            'tag': tag,
            'page': page,
            'current_time': current_time,
            'popular_tours': popular_tours,
            'all_tours': all_tours,
            'all_tags': all_tags,
            'all_category': all_category,
            'category': category,
            'last_tours': last_tours,
        })


def detail_of_tour(request, id):
    tour = get_object_or_404(Tour, id=id)
    popular_tours = Tour.objects.filter(popular=True)
    all_tags = Tour.tags.all()
    all_category = Category.objects.all()

    comments = tour.comments.filter(active=True)
    comment_count = comments.count()

    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)

        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.name = request.user
            new_comment.tour = tour
            new_comment.save()
            return redirect('tour_detail', id=id)
        else:
            comment_form.username = 'Signup'
    else:
        tour.views += 1
        tour.save()
        comment_form = CommentForm()

    return render(request, 'tour/tour_detail.html', {'tour': tour,
                                                     'comments': comments,
                                                     'new_comment': new_comment,
                                                     'comment_form': comment_form,
                                                     'popular_tours': popular_tours,
                                                     'all_category': all_category,
                                                     'all_tags': all_tags,
                                                     'comment_count': comment_count,
                                                     })

class ContactListView(ListView):
    model = Contact
    template_name = 'tour/contact.html'


def about_detail(request):
    about = []
    if About.objects.all():
        about = About.objects.all()[0]
    members = Members.objects.all()
    comments = Comment.objects.filter(active=True)
    popular_tours = Tour.objects.filter(popular=True)
    comments_texts = []
    for c in comments:
        comments_texts.append(c.text)

    return render(request, 'pages/about-us.html', {'about': about,
                                                   'members': members,
                                                   'comments_texts': comments_texts,
                                                   'popular_tours': popular_tours,
                                                   })


class MembersListView(ListView):
    model = Members
    template_name = 'pages/about-us.html'
    context_object_name = 'members'


class SearchView(TemplateView):
    template_name = "tour/result.html"

    def get(self, request, *args, **kwargs):

        search = request.GET.get('search')
        tours = Tour.objects.all()
        # results = tours.filter(Q(title__icontains=search) | Q(text__icontains=search))
        results = []
        for i in tours:
            if search.lower() in i.title.lower() or search.lower() in i.text.lower():
                results.append(i)
        return render(request, self.template_name, context={
            'results':results
        })

    def post(self, request, *args, **kwargs):
        return render(request, self.template_name, context={
        })

templates/tour/categories_for_filter.html
<aside class="single_sidebar_widget post_category_widget">
    <h4 class="widget_title">Tour Categories</h4>
    <ul class="list cat-list">
        {% for category in all_category %}
            <li><a href="{% url "tour_list_by_category" category.id %}">{{ category }}</a></li>
        {% endfor %}
        <li><a href="{% url 'tourlist' %}">All tours</a></li>
    </ul>
    <div class="br"></div>
</aside>

templates/tour/categories_for_home.html
<section class="feature-area section_gap_top">
		<div class="container">
			<div class="row align-items-end justify-content-left">
				<div class="col-lg-12">
					<div class="main_title">
						<p>We’re Offering these Popular Services</p>
						<h1>Getting Adventure with Services</h1>
						<span class="title-widget-bg"></span>
					</div>
				</div>
			</div>
			<div class="row">
				<!-- single-feature -->
                {% for category in all_category %}
				<div class="col-lg-3 col-md-6">
					<div class="single-feature">
						<div class="feature-details">
							<h5>{{ category.category }}</h5>
							<p>
								{{ category.description|truncatewords:10 }}
							</p>
							<a href="{% url 'category_detail' category.id %}" class="primary-btn mb-40">Read More</a>
						</div>
						<div class="feature-thumb">
							<img class="img-fluid" src="{{ category.photo.url }}" alt="">
						</div>
					</div>
				</div>
                {% endfor %}
			</div>
		</div>
	</section>

templates/tour/categories_info.html
<section class="blog_categorie_area">
    <div class="container">
        <div class="row">
            {% for category in all_category %}
            <div class="col-lg-3">
                <div class="categories_post">
                    <a href="{% url "tour_list_by_category" category.id %}"><img src="{{ category.photo.url }}" alt="post"></a>
                    <div class="categories_details">
                        <div class="categories_text">
                            <a href="{% url "tour_list_by_category" category.id %}"><h5>{{ category.category }}</h5></a>
                            <div class="border_line"></div>
                            <p>{{ category.description|truncatewords:4 }}</p>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

templates/tour/category_detail.html
{% extends 'main/base.html' %}

{% load static %}

{% block body %}
    	<section class="home_banner_area">
		<div class="banner_inner">
			<div class="container">
				<div class="row fullscreen d-flex align-items-center justify-content-center">
					<div class="banner_content">
						<p>Plan a trip to Santorini Village</p>
						<h2>Taxa Adventure</h2>
					</div>
				</div>
			</div>
		</div>
	</section>
    <section class="blog_area single-post-area section_gap">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 posts-list">
                    <div class="single-post row">
                        <div class="col-lg-12">
                            <div class="feature-img">
                                <img class="img-fluid" src="{{category.photo.url}}" style="width: 500px !important;" alt="...">
                            </div>
                        </div>
                        <div class="col-lg-9 col-md-9 blog_details">
                            <h2>{{ category.category }}</h2>
                            <p class="excert">
                              {{ category.description }}
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock body %}

templates/tour/contact.html
{% extends 'main/base.html' %}
{% load static %}
{% block body  %}
    <section class="banner_area ">
    <div class="banner_inner overlay d-flex align-items-center">
        <div class="container">
            <div class="banner_content">
                <div class="page_link">
                    <a href="{% url 'home' %}">Home</a>
                    <a href="{% url 'contact' %}">Contact</a>
                </div>
                <h2>Contact</h2>
            </div>
        </div>
    </div>
</section>
    <section class="contact_area section_gap">
    <div class="container">
        <a class="dg-widget-link" href="http://2gis.kg/bishkek/firm/70000001033531208/center/74.59907770156862,42.87629432212129/zoom/16?utm_medium=widget-source&utm_campaign=firmsonmap&utm_source=bigMap">Посмотреть на карте Бишкека</a><div class="dg-widget-link"><a href="http://2gis.kg/bishkek/firm/70000001033531208/photos/70000001033531208/center/74.59907770156862,42.87629432212129/zoom/17?utm_medium=widget-source&utm_campaign=firmsonmap&utm_source=photos">Фотографии компании</a></div><div class="dg-widget-link"><a href="http://2gis.kg/bishkek/center/74.599027,42.875843/zoom/16/routeTab/rsType/bus/to/74.599027,42.875843╎Pandora flowers, салон цветов?utm_medium=widget-source&utm_campaign=firmsonmap&utm_source=route">Найти проезд до Pandora flowers, салон цветов</a></div><script charset="utf-8" src="https://widgets.2gis.com/js/DGWidgetLoader.js"></script><script charset="utf-8">new DGWidgetLoader({"width":640,"height":600,"borderColor":"#a3a3a3","pos":{"lat":42.87629432212129,"lon":74.59907770156862,"zoom":16},"opt":{"city":"bishkek"},"org":[{"id":"70000001033531208"}]});</script><noscript style="color:#c00;font-size:16px;font-weight:bold;">Виджет карты использует JavaScript. Включите его в настройках вашего браузера.</noscript>        <div class="row">
            <div class="col-lg-3">
                <div class="contact_info">
                    {% for contact in contact_list %}
                    <div class="info_item">
                        <i class="lnr lnr-home"></i>
                        <h6>{{ contact.address }}</h6>
                        <p>{{ contact.address_text }}</p>
                    </div>
                    <div class="info_item">
                        <i class="lnr lnr-phone-handset"></i>
                        <h6><a href="#">{{ contact.number }}</a></h6>
                        <p>{{ contact.number_text }}</p>
                    </div>
                    <div class="info_item">
                        <i class="lnr lnr-envelope"></i>
                        <h6><a href="#">{{ contact.email }}</a></h6>
                        <p>{{ contact.email_text }}</p>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="col-lg-9">
                <form class="row contact_form" action="contact_process.php" method="post" id="contactForm"
                      novalidate="novalidate">
                    <div class="col-md-6">
                        <div class="form-group">
                            <input type="text" class="form-control" id="name" name="name" placeholder="Enter your name">
                        </div>
                        <div class="form-group">
                            <input type="email" class="form-control" id="email" name="email"
                                   placeholder="Enter email address">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" id="subject" name="subject"
                                   placeholder="Enter Subject">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <textarea class="form-control" name="message" id="message" rows="1"
                                      placeholder="Enter Message"></textarea>
                        </div>
                    </div>
                    <div class="col-md-12 text-right">
                        <button type="submit" value="submit" class="primary-btn text-uppercase">Send Message</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/tour/last_tours.html
<section class="blog_categorie_area">
    <div class="container">
        <div class="row">
            {% for tour in last_tours %}
            <div class="col-lg-4">
                <div class="categories_post">
                    <a href="{% url 'tour_detail' tour.id %}"><img src="{{ tour.photo.url }}" alt="post"></a>
                    <div class="categories_details">
                        <div class="categories_text">
                            <a href="{% url 'tour_detail' tour.id %}"><h5>{{ tour.title }}</h5></a>
                            <div class="border_line"></div>
                            <p>{{ tour.text|truncatewords:4 }}</p>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

templates/tour/result.html
{% extends 'main/base.html' %}
{% load static %}
{% block body %}
    <section class="banner_area ">
        <div class="banner_inner overlay d-flex align-items-center">
            <div class="container">
                <div class="banner_content">
                    <div class="page_link">
                        <a href="{% url 'home' %}">Home</a>
                        <a href="{% url 'tourlist' %}">Tours</a>
                    </div>
                    <h2>Tours</h2>
                </div>
            </div>
        </div>
    </section>
    <!--================End Home Banner Area =================-->

    <!--================Blog Area =================-->
    <section class="blog_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="blog_left_sidebar">
                        {% for item in results %}
                            <article class="row blog_item">
                                <div class="col-md-3">
                                    <div class="blog_info text-right">
                                        <ul class="blog_meta list">
                                            <li><a href="#">{{ item.created }}<i class="lnr lnr-calendar-full"></i></a>
                                            </li>
                                            <li><a href="#">Views {{ item.views }}<i class="lnr lnr-eye"></i></a></li>
                                            <li><a href="#">Comments {{ item.comments.count }}<i
                                                    class="lnr lnr-bubble"></i></a></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="col-md-9">
                                    <div class="blog_post">
                                        <a href="{% url 'tour_detail' item.id %}"><img src="{{ item.photo.url }}"
                                                                                       style="..." alt="..."/></a>
                                        <div class="blog_details">
                                            <a href="{% url 'tour_detail' item.id %}">
                                                <h2>{{ item.title }}</h2>
                                            </a>
                                            <p>{{ item.text|truncatewords:30|linebreaks }}</p>
                                            <a href="{% url 'tour_detail' item.id %}" class="blog_btn">View More</a>
                                        </div>
                                    </div>
                                </div>
                            </article>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/tour/tour_list.html
{% extends 'main/base.html' %}
{% load static %}
{% block body  %}
<section class="banner_area ">
    <div class="banner_inner overlay d-flex align-items-center">
        <div class="container">
            <div class="banner_content">
                <div class="page_link">
                    <a href="{% url 'home' %}">Home</a>
                    <a href="{% url 'tourlist' %}">Tours</a>
                </div>
                <h2>Tours</h2>
            </div>
        </div>
    </div>
</section>
<!--================End Home Banner Area =================-->

<!--================Blog Categorie Area =================-->
{% include 'tour/categories_info.html' %}
<!--================Blog Categorie Area =================-->

<!--================Blog Area =================-->
<section class="blog_area">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="blog_left_sidebar">
                {% if tag %}
                    <h2>Tours tagged with "{{ tag.name }}"</h2>
                {% endif %}
                    {% for item in tours %}
                    <article class="row blog_item">
                        <div class="col-md-3">
                            <div class="blog_info text-right">
                                <div class="post_tag">
                                    <a class="active" href="#"></a>
                                    <p class="tags">
                                        Tags:
                                        {% for tag in all_tags %}
                                            <a href="{% url "tour_list_by_tag" tag.slug %}">
                                                {{ tag }}
                                            </a>
                                            {% if not forloop.last %}, {% endif %}
                                        {% endfor %}
                                    </p>
                                </div>
                                <ul class="blog_meta list">
                                    <li><a href="#">{{ item.created }}<i class="lnr lnr-calendar-full"></i></a></li>
                                    <li><a href="#">Views {{ item.views }}<i class="lnr lnr-eye"></i></a></li>
                                    <li><a href="#">Comments {{ item.comments.count }}<i class="lnr lnr-bubble"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-md-9">
                            <div class="blog_post">
                                <a href="{% url 'tour_detail' item.id %}"><img src="{{ item.photo.url }}" style="..." alt="..."/></a>
                                <div class="blog_details">
                                    <a href="{% url 'tour_detail' item.id %}">
                                        <h2>{{ item.title }}</h2>
                                    </a>
                                    <p>{{ item.text|truncatewords:30|linebreaks }}</p>
                                    <a href="{% url 'tour_detail' item.id %}" class="blog_btn">View More</a>
                                </div>
                            </div>
                        </div>
                    </article>
                    {% endfor %}
                {% include 'pagination.html' with page=tours %}
                </div>
            </div>
            <div class="col-lg-4">
                <div class="blog_right_sidebar">
                    <aside class="single_sidebar_widget popular_post_widget">
                        <h3 class="widget_title">Popular Tours</h3>
                        {% for tour in popular_tours %}
                            <div class="media post_item">
                                <a href="{% url 'tour_detail' tour.id %}"><img src="{{ tour.photo.url }}" alt="post" width="120px"></a>
                                <div class="media-body">
                                    <a href="{% url 'tour_detail' tour.id %}">
                                        <h3>{{ tour.title }}</h3>
                                    </a>
                                    <p>{{ tour.created }}</p>
                                </div>
                            </div>
                        {% endfor %}
                        <div class="br"></div>
                    </aside>
                    <aside class="single_sidebar_widget ads_widget">
                        <a href="#"><img class="img-fluid" src="{% static 'img/blog/add.jpg' %}" alt=""></a>
                        <div class="br"></div>
                    </aside>
                {% include 'tour/categories_for_filter.html' %}
                    <aside class="single-sidebar-widget tag_cloud_widget">
                        <h4 class="widget_title">Tag Clouds</h4>
                        <ul class="list">
                            {% for tag in all_tags %}
                                <li><a href="{% url "tour_list_by_tag" tag.slug %}">{{ tag }}</a></li>
                            {% endfor %}
                        <li><a href="{% url 'tourlist' %}">All tours</a></li>
                        </ul>
                    </aside>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}